# Generated by Django 5.1 on 2024-08-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='letterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromNumber', models.CharField(max_length=100)),
                ('pdfFile', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='lettermaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.CharField(max_length=100)),
                ('Body', models.TextField()),
                ('Footer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='currentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromNumber', models.CharField(max_length=100)),
                ('progress', models.CharField(default='Header', max_length=100)),
                ('letterItems', models.ManyToManyField(blank=True, to='botapp.lettermaking')),
            ],
        ),
    ]
