# Generated by Django 5.1 on 2024-08-19 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentprogress',
            name='letterItems',
        ),
        migrations.AddField(
            model_name='currentprogress',
            name='letterDetails',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botapp.lettermaking'),
        ),
    ]
