# Generated by Django 5.1 on 2024-08-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_remove_currentprogress_letteritems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentprogress',
            name='letterDetails',
        ),
        migrations.AddField(
            model_name='currentprogress',
            name='letterItems',
            field=models.ManyToManyField(blank=True, to='botapp.lettermaking'),
        ),
    ]
