# Generated by Django 4.2.15 on 2024-08-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0003_remove_currentprogress_letterdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettermaking',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
