# Generated by Django 4.2.15 on 2024-08-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0004_lettermaking_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lettermaking',
            name='photo',
        ),
        migrations.AddField(
            model_name='lettermaking',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='letter_images/'),
        ),
    ]
